package com.example.demo;

import javax.script.ScriptException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class Calc {

	// This means to get the bean called userRepository
	// Which is auto-generated by Spring,
	@Autowired
	Calculator calculator;

	// This means URL's start with /calcjs (after Application)
	@RequestMapping(path = "/calcjs", method = RequestMethod.POST)
	@ResponseBody // @ResponseBody means the returned String is the response
	public String solveMathExprJS(@RequestBody MathExpression mathExpr) {
		String calc;
		try {
			calc = calculator.calcWithJs(mathExpr.getMathExpr());
		} catch (ScriptException e) {
			e.printStackTrace();
			return "Failed to parse the equation" + mathExpr.getMathExpr() + e;
		}
		return calc;
	}

	@RequestMapping(path = "/calc", method = RequestMethod.POST)
	@ResponseBody
	public String solveMAthExpr(@RequestBody MathExpression mathExpr) {
		String calc;
		try {
			calc = calculator.calcWithSyaAlgo(mathExpr.getMathExpr());
		} catch (Exception e) {
			e.printStackTrace();
			return "Failed to parse the equation" + mathExpr.getMathExpr()+ e;
		}
		return calc;
	}

	@RequestMapping(path = "/calc", method = RequestMethod.GET)
	@ResponseBody
	public String userGuide() {
		return "Please send a json format like { \"mathExpr\":\"1+2+3\" }";
	}

}
